name: WinDooMVoteShop
main: me.krconv.WinDooMVoteShop.WinDooMVoteShop
version: 1.0
softdepend: [Vault]
description: >
             WinDooM's VoteShop Plugin!
commands:
  voteshop:
    description: WinDooM's VoteShop Plugin!